name: Automated Tests

on: [push]

jobs:
  run-tests:
    name: Run Automated Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Test Case 1 - Ten Numbers
      run: |
        python find_lowest_number.py test_data/test1_input.txt test1_output.txt
        diff test1_output.txt test_data/test1_expected.txt

    - name: Test Case 2 - One Number
      run: |
        python find_lowest_number.py test_data/test2_input.txt test2_output.txt
        diff test2_output.txt test_data/test2_expected.txt

    - name: Test Case 3 - Blank File
      run: |
        python find_lowest_number.py test_data/test3_input.txt test3_output.txt
        diff test3_output.txt test_data/test3_expected.txt
